# Generated by Django 4.2 on 2023-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='consultation_id',
            field=models.CharField(max_length=100),
        ),
    ]
